add relcool for building release

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -50,12 +50,24 @@ if [ ! -e "rebar" ]; then
   cp ${bpdir}/opt/rebar ./
 fi
 
+if [ ! -e "relcool" ]; then
+    echo "-----> Installing relcool from buildpack"
+    cp ${bpdir}/opt/relcool ./
+fi
+
 echo "-----> Building with Rebar"
 unset GIT_DIR
 ./rebar get-deps compile 2>&1 | sed -u 's/^/       /'
 if [ ${PIPESTATUS[0]} -ne 0 ]; then
   echo "-----> Build failed"
   exit 1
+fi
+
+echo "-----> Creating release with relcool"
+./relcool 2>&1 | sed -u 's/^/       /'
+if [ ${PIPESTATUS[0]} -ne 0 ]; then
+    echo "-----> Release failed"
+    exit 1
 fi
 
 echo "-----> Build succeeded"
